version: '3.4'

services:
  smartalertapi:
    image: ${DOCKER_REGISTRY-}smartalertapi
    build:
      context: .
      dockerfile: SmartAlertApi/Dockerfile
    ports:
      - 4015:443 

  db:
    image: postgis/postgis
    container_name: psql
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Pa$$w0rd
      - POSTGRES_USER=appuser

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      -  5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - my-data:/var/lib/pgadmin

volumes:
 pgdata:
 my-data: